### ISSUE TITLE
Leon's Portfolio

### ISSUE THREAD

**Issue by MitjaCH** [thenix05/Git_Md_Gruppe3#2]
# Nachricht an Leon

Liebe Grüße, Leon!

Es ist mir aufgefallen, dass du Teile meines Portfolios übernommen hast. Dieser Umstand hat bei mir Unbehagen ausgelöst, und ich möchte diesbezüglich einige Punkte ansprechen.

Grundsätzlich ist es wichtig, die Urheberrechte zu respektieren und geistiges Eigentum zu schützen. Das Abschreiben von Inhalten, insbesondere aus einem Portfolio, stellt eine Verletzung dieser Prinzipien dar. Es ist nicht nur ethisch fragwürdig, sondern kann auch rechtliche Konsequenzen nach sich ziehen.

Um mögliche Missverständnisse aus dem Weg zu räumen, bitte ich dich, in Zukunft eigenständige Inhalte zu erstellen und darauf zu achten, die Arbeit anderer nicht unerlaubt zu verwenden. Diese Vorgehensweise trägt nicht nur zur Wahrung von Integrität und Fairness bei, sondern stärkt auch deine eigenen Fähigkeiten und Kreativität.

Es ist mir wichtig, dass wir diese Angelegenheit klären, um etwaige Konsequenzen zu vermeiden. Falls du Fragen hast oder eine Diskussion darüber wünschst, stehe ich gerne zur Verfügung.

Mit freundlichen Grüßen,
Mitscha

**Comment by nxkzty** [comment]
Lieber Mitscha,

ich hoffe, diese Nachricht erreicht dich wohlauf. Es tut mir leid, von deinem Unbehagen zu hören, aber ich muss betonen, dass die Behauptung, Leon Teile deines Portfolios übernommen habe, nicht den Tatsachen entspricht.

Leon hat stets eigenständige Inhalte erstellt und sich darauf konzentriert, seine individuellen Fähigkeiten und Kreativität zu präsentieren. Es wäre unangebracht und respektlos, falsche Anschuldigungen zu erheben und jemandem das Abschreiben vorzuwerfen, ohne handfeste Beweise zu haben.

Ich schlage vor, dass wir in einer konstruktiven Art und Weise über dieses Missverständnis sprechen, um eventuelle Unklarheiten aus dem Weg zu räumen. Wir alle sollten bestrebt sein, die Integrität und Fairness zu wahren, und ich bin sicher, dass eine offene Kommunikation dabei hilfreich sein kann.

Wenn du weitere Fragen hast oder eine Diskussion darüber wünschst, stehe ich gerne zur Verfügung. Lass uns gemeinsam eine Lösung finden, die für alle Beteiligten akzeptabel ist.

Mit freundlichen Grüßen,
leon

**Comment by MitjaCH** [comment]
Lieber Leon,

es ist bedauerlich zu sehen, dass du offensichtliche Unannehmlichkeiten in Kauf nimmst, um Leon in Schutz zu nehmen. Es wirkt jedoch wenig überzeugend, die Behauptungen von Mitscha ohne weiteres abzutun, insbesondere wenn es um die Übernahme von Portfolio-Inhalten geht.

Es wäre vielleicht angebracht, klarzustellen, dass du nicht in der Position bist, die Handlungen und Absichten von Leon in jedem Detail zu kennen. Statt sofort zu behaupten, dass Mitscha falsche Anschuldigungen erhebt, wäre es vielleicht sinnvoller, die Angelegenheit in einem respektvollen und sachlichen Gespräch zu klären.

Eine direkte Konfrontation mit Beleidigungen und respektlosem Verhalten ist selten der beste Weg, um Konflikte zu lösen. Vielleicht wäre es klüger, sich auf die Fakten zu konzentrieren und gemeinsam nach einer Lösung zu suchen, anstatt vorschnelle Urteile zu fällen.

Mit freundlichen Grüßen,
Eine neutrale Beobachterin

**Comment by nxkzty** [comment]
Hallo Neutrale Person
Halt eif dein Maul

Böse grüsse Leon

**Comment by MitjaCH** [comment]
Lieber Leon.

Du dummer Schwein das ist sehr respektlos.!!!!!!!

Sehr böse grüsse 😈 

Mitscha (Einen neutrale Person)

**Comment by nxkzty** [comment]
Sorry leute :-(

**Comment by MitjaCH** [comment]
hdf

**Comment by nxkzty** [comment]
Hallo Mitscha
Ich hoffe diese Nachricht nehmen sie Persönlich
Halt eif dein Maul

Mit bösen absichten und bösen Grüssen

Leon
